"""initial migration

Revision ID: b76f487c0ae9
Revises: 
Create Date: 2026-07-14 14:49:25.200123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b76f487c0ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_info')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_name'))

    op.drop_table('programs')
    with op.batch_alter_table('map_hotspots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_hotspots_map_id'))

    op.drop_table('map_hotspots')
    with op.batch_alter_table('guide_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_items_section'))

    op.drop_table('guide_items')
    op.drop_table('campus_maps')
    with op.batch_alter_table('school_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_locations_hotspot_id'))

    op.drop_table('school_locations')
    with op.batch_alter_table('bili_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bili_sub_token'))

    with op.batch_alter_table('bili_ups', schema=None) as batch_op:
        batch_op.alter_column('follower_count',
               existing_type=mysql.INTEGER(),
               comment='粉丝数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('bili_videos', schema=None) as batch_op:
        batch_op.alter_column('pub_datetime',
               existing_type=mysql.DATETIME(),
               comment='发布日期时间',
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_post_fulltext', ['title', 'content'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('product_sources', schema=None) as batch_op:
        batch_op.alter_column('latest_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('footer_qr1')
        batch_op.drop_column('logo')
        batch_op.drop_column('footer_qr2')
        batch_op.drop_column('bg_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), server_default=sa.text("''"), nullable=True))
        batch_op.add_column(sa.Column('footer_qr2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), server_default=sa.text("''"), nullable=True))
        batch_op.add_column(sa.Column('logo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), server_default=sa.text("''"), nullable=True))
        batch_op.add_column(sa.Column('footer_qr1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('product_sources', schema=None) as batch_op:
        batch_op.alter_column('latest_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_is_published'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index('ix_post_fulltext', mysql_prefix='FULLTEXT')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_1'), 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('bili_videos', schema=None) as batch_op:
        batch_op.alter_column('pub_datetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='发布日期时间',
               existing_nullable=True)

    with op.batch_alter_table('bili_ups', schema=None) as batch_op:
        batch_op.alter_column('follower_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='粉丝数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('bili_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bili_sub_token'), ['token'], unique=False)

    op.create_table('school_locations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('summary', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('hotspot_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['hotspot_id'], ['map_hotspots.id'], name=op.f('school_locations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('school_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_locations_hotspot_id'), ['hotspot_id'], unique=False)

    op.create_table('campus_maps',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('guide_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('section_label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('guide_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_items_section'), ['section'], unique=False)

    op.create_table('map_hotspots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('map_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('link_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True),
    sa.Column('x_pos', mysql.FLOAT(), nullable=True),
    sa.Column('y_pos', mysql.FLOAT(), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['campus_maps.id'], name=op.f('map_hotspots_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('map_hotspots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_hotspots_map_id'), ['map_id'], unique=False)

    op.create_table('programs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_name'), ['name'], unique=False)

    op.create_table('contact_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('link_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True),
    sa.Column('qr_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
